filebeat.inputs:
  - type: filestream
    id: docker-containers
    parsers:
      - container: {}
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
