# ===== FTP Basics ===== #
listen=YES
listen_ipv6=NO
listen_port=21
# ===== AUTHENTIFICATION ===== #
anonymous_enable=NO
local_enable=YES
# Autorise l'ecriture (upload, delete, rename ...)
write_enable=YES
# Permissions par defaut des fichiers uploades
local_umask=022
# ===== USERS PARAMS ===== #
userlist_enable=NO
# userlist_file=/etc/vsftpd.userlist
userlist_deny=NO
user_sub_token=$USER
# ===== SECURITY ===== #
chroot_local_user=YES
allow_writeable_chroot=YES
# ===== ROOT FTP file ===== #
local_root=/var/www/html/wordpress
# ===== PASSIVE MODE ===== #
pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010
pasv_address=ftp
# ===== LOGS & TIMEOUT ===== #
xferlog_enable=YES
xferlog_std_format=YES
idle_session_timeout=600
data_connection_timeout=120
seccomp_sandbox=NO